version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    labels:
      - github_actions
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: uv
    versioning-strategy: increase
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    labels:
      - dependencies
    groups:
      actions:
        patterns: ["*"]
