version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "dev"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    target-branch: "dev"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
